### ISSUE TITLE
Username must be supplied to trick agithub to use the token

### ISSUE THREAD

**Issue by kjkuan** [mozilla/agithub#11]
Hi,

I'm not sure if it's intentional, but with github, a token is all that is needed to make an authorized request. However, according to `agithub`'s logic, an username must be provided in order for it to add the authorization header that includes the token.

It's not a big deal though, one can always just supply a dummy username or add the authorization header for each request.

Thanks

**Comment by jpaugh** [comment]
Okay. Thanks for catching that. I'm not too savy with token authentication, to tell you the truth. I'll fix this when I get some time. (Or, on the other hand, patches are welcome!)
