### ISSUE TITLE
Any nice way to specify the path as a variable?

### ISSUE THREAD

**Issue by hamishwillee** [mozilla/agithub#13]
The URL is passed in a daisy chain, e.g.
status, data = g.repos.hamishwillee.docs.readme.get(headers= {'Accept':'application/vnd.github.3.raw+json'} )
Is there any way to pass in the repo (e.g. "hamishwillee.docs" as a variable (e.g. options.repo). 

As an aside, while it is often useful to have a "python-esque" API, having access to everything in a more or less unbreakable way is very clever :-)

**Comment by jpaugh** [comment]
Yes there is a way, because it is possible to use indexing syntax lieu of member synrtax. I believe my comment on issue #14 demonstrates this adequately.

**Comment by hamishwillee** [comment]
Thank you, I believe it does.
