### ISSUE TITLE
Can't create new files - problems parsing JSON

### ISSUE THREAD

**Issue by hamishwillee** [mozilla/agithub#14]
What I want to do is create a file in my repository at an arbitrary path. So for example "fred/mytext.txt"

Unfortunately I either get an error 400 for "Problems parsing JSON" or "not found".

```
   filetext1 = 'This is my test file text. It has to be something, why not this.'
   encoded_content = base64.b64encode(filetext1)    #must be Base64 encoded.
   print 'encoded content: %s' % encoded_content
   #Creating a file
```

The documentation reads like I should do it like this:

```
status, data = g.repos.hamishwillee.ardupilot_wordpress_sources.contents.fred/mytestfile1.txt.put(message= 'Adding a new file', content=encoded_content )
```

but I get an error "NameError: name 'mytestfile1' is not defined" because of the period in .txt. So then I tried putting this information in a path variable:

```
status, data = g.repos.hamishwillee.ardupilot_wordpress_sources.contents.put(path="fred/mytestfile1.txt",message= 'Adding a new file', content=encoded_content )
```

With the URL/debug:

```
  PUT
  /repos/hamishwillee/ardupilot_wordpress_sources/contents?  content=VGhpcyBpcyBteSB0ZXN0IGZpbGUgdGV4dC4gSXQgaGFzIHRvIGJlIHNvbWV0aGluZywgd2h5IG5vdCB0aGlzLg%3D%3D&path=fred%2Fmytestfile1.txt&message=Adding+a+new+file

  404
  {u'documentation_url': u'https://developer.github.com/v3', u'message': u'Not Found'}
```

I also tried without the "fred" path.

I appreciate this might be an error in my usage, but would be great to have an example of this approach working.

**Comment by jpaugh** [comment]
Hello. Thank you for your detailed feedback. I have not had much feedback lately, and I apologize for my late response.

The README shows how to handle this case in the [sample app](https://github.com/jpaugh/agithub#example-app) at item 4. _If you can provide a better explanation/example of this feature, please do!_

In regard to your specific case, however: Have you tried the following?

```
g.repos.hamishwillee.ardupilot_wordpress_sources.contents.["fred/mytestfile1.txt."].put(message= 'Adding a new file', content=encoded_content )
```

Note that I put `"fred/mytestfil1.txt"` in quotation marks, and used "dictionary item" syntax instead of "object member" syntax. I added the dict syntax specifically to handle cases like this, where the usual syntax would throw an error. Consider also the case where a number is needed:

```
g.some.path.paginated[4].get()
```

**Comment by hamishwillee** [comment]
Thanks very much for this. I ended up just making command line calls on git to do what I needed while waiting for this response. I plan to go back and do it properly using your API but not quite yet (hard to go back when something is working!). 

Anyway, thanks for the explanation. I had read the sample app and the indexing approach didn't make sense to me. Looking again with your additional examples above (thanks!) it does indeed make perfect sense. 

What might help make it even more clear is to add a few words explaining the real benefits of your code fragment.

So (for example)

Sometimes, it is inconvenient (or impossible) to refer to a URL as a chain of attributes, so indexing syntax is provided as well. It behaves exactly the same.

For example, using the normal syntax we can get the issue for a specific user and repo as shown:

> > > g.repos.jpaugh.repla.issues[1].get()
> > > (200, { 'id': '#blah', ... })

But if you can use the indexing syntax if you don't want to hard code the user or repo details:

> > > mylogin, myrepo = 'jpaugh', 'braille-converter'
> > > g.repos[mylogin][myrepo].milestones.get(state='open', sort='completeness')
> > > (200, [ list, of, milestones ])

Anyway, thanks again!

**Comment by jpaugh** [comment]
I appreciate your input. If you feel you can improve the description, please make a pull request. (You have a better perspective of how the wording is misleading.)
