### ISSUE TITLE
Straw poll: more encompassing name (ends April 1 23:59)

### ISSUE THREAD

**Issue by kwill** [mozilla/agithub#2]
This project is no longer limited to just the Github REST API, so a more encompassing name is appropriate. Please submit suggestions below and vote below.

* One suggestion per comment: shortname/Long Name
* Vote with thumbs up or down (others ignored)
* Suggestion window ends April 1 23:59 [AoE](https://en.wikipedia.org/wiki/Anywhere_on_Earth)
* Final decision (tie-breaking, valid entry, veto, etc) by @gene1wood

**Comment by gene1wood** [comment]
@kwill Agreed. Feel like putting together a name nomination window and then a poll/vote once we've got a body of nominated names? We should probably run it for a good enough chunk of time to get a good number of responses (both for name ideas and for votes) which I'm assuming should be fine as a name change isn't an urgent thing. We'd want shortname longname combinations (e.g. arestclient/Agnostic REST client)

**Comment by kwill** [comment]
@gene1wood Edited my first comment to set a nomination-and-voting window for just under a month (above).

**Comment by kwill** [comment]
arestclient/Agnostic REST client

**Comment by kwill** [comment]
agithub/The Agnostic GitHub API (in other words, don't change it)

**Comment by gene1wood** [comment]
As I've gotten control of the original agithub repo, I'm going to delete this fork, transfer the repo, then open a new issue with the content from this issue. There won't be a redirect there from this issue unfortunately, I'll just copy paste.
