### ISSUE TITLE
params vs body in PUT request

### ISSUE THREAD

**Issue by zeph** [mozilla/agithub#24]
I had to switch the usage of ```PUT /teams/:id/repos/:org/:repo```
 - https://developer.github.com/v3/orgs/teams/#add-or-update-team-repository

this way...
```python
- status, data = gh.teams[infra_central_id].repos[org['login']][repo_name].put(permission="push")
- if status != 204:
-    print colored('X', 'red'),

+ payload={"permission": "push"}
+ status, data = gh.teams[infra_central_id].repos[org['login']][repo_name].put(body=payload)
+ if status != 204:
+    print colored('X', 'red'),
```

either else it would have not worked

is it intended, or a bug worth looking at?

**Comment by gene1wood** [comment]
This behavior is intended. Here's some [info in the docs about using the `body` argument](https://github.com/jpaugh/agithub/blob/master/README.md#body).
