### ISSUE TITLE
Needs a new maintainer

### ISSUE THREAD

**Issue by jpaugh** [mozilla/agithub#35]
AGithub has been a fun project, and I'm thrilled about the interest and fixes that have come from the open source community since it has been released. Thank you all for using and improving AGithub!

Right now, I'm looking for a new maintainer to replace me. If you are interested in the future of this project and have the time, consider nominating yourself as a potential maintainer in a comment to this issue. If you know of someone else who might be interested (preferably someone who has shown some activity with the project), mention them in a comment.

Additionally, if you support the nomination of a particular candidate, speak up! No open-source project can survive without community involvement. I will choose the person who seems most eager, and most able to shepherd the project going forward. I will give that person commit access, and point all new-comers to their repo, using whatever tools GitHub has made available for doing so. This person should then talk to @jaredhobbs about gaining access to the [Pypi repo](https://github.com/jpaugh/agithub/issues/17#issuecomment-343295987). I will support the transition however I can.

## Why?
Regretfully, I no longer find it personally gratifying to work on it. Any future work on AGithub has thus-far been impeded by my unresponsiveness to issues and pull requests. Worse than that, I see no future direction for the project, viewing it as largely complete, as my need for a Python REST client  is limited to the occasional one-off. I don't foresee this changing in the future, as I'm primarily focusing on Haskell, Java and C# development, and have been for the past few years.

**Comment by gene1wood** [comment]
@jpaugh I'd be open to helping. I would imagine what would be even better than designating myself as a single new maintainer would instead be to designate a handful of maintainers (if there is enough interest).

As you've said the project is largely complete. It looks like a small number of issues/PRs. I would imagine interest in the project will slowly decrease over time as adoption of the new [GitHub GraphQL V4 API](https://developer.github.com/v4/) increases.

If you wanted you could also [transfer](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) the `agithub` repository to the [mozilla](https://github.com/mozilla) organization which I work within and help administer which would at least decouple the project from a single human and might facilitate a community maintenance model better.

**Comment by nnja** [comment]
@gene1wood Moving it to the `mozilla` organization sounds like a good idea. I'd also like to propose renaming the project. I've used it quite a few times for rapid API prototyping for many different REST APIs, not just github. I find the project name misleading.  

I currently can't commit the time to becoming a maintainer, but I can volunteer some time to help with pull requests and issues where needed.

**Comment by gene1wood** [comment]
@jpaugh Have you had any thought on [this](https://github.com/jpaugh/agithub/issues/35#issuecomment-345005604) since November?

**Comment by gene1wood** [comment]
@jpaugh Even just adding me as a maintainer, in addition to you, would be a useful interim step if you're open to it.

**Comment by jarekr** [comment]
I have recently discovered this library and I second all of @nnja 's comments. It has been surprisingly useful given how simple it is.

I'd also be willing to help out where needed, but can't really commit to being a maintainer.

**Comment by lofidevops** [comment]
You could also consider admin and maintenance support from @jazzband (in combination with any of the suggestions and offers above).

I agree that the name is confusing given what the library is capable of (and as GitHub offers non-REST options). Maybe it would be easiest if someone made a friendly fork with a new name?

**Comment by nnja** [comment]
@kwill considering the nonresponsiveness of the creator and the large amount of interest in the project, I agree that a friendly fork with a rename and full attribution to @jpaugh is the next best step. I nominate @gene1wood to take over so the project can live within the Mozilla organization.

**Comment by gene1wood** [comment]
I'd say @jpaugh wants to hand off maintenance of this project and just isn't seeing these messages (considering he opened this issue). Let me see if I can reach him through some offline method.

Since there seems strong interest from everyone including @jpaugh to rename the project I don't know that a fork is needed to achieve that, just getting @jpaugh to add someone as a maintainer really.

Ya, I'll see if I can find an email address to reach him at.

**Comment by nnja** [comment]
@gene1wood That sounds great, thank you for owning! How about we set a time limit for this process? If we can't find another way to contact @jpaugh, or if we find other contact methods and they don't respond in a month, maybe two, can we go ahead with a fork?

Regardless, I'd be happy to join in as a contributor. This project has saved me tons of time!

**Comment by nnja** [comment]
@gene1wood Heads up -- his email address is posted on his github profile page! Hope that helps.

**Comment by gene1wood** [comment]
@nnja Ya, time limit sounds good to me. March 1st? I emailed @jpaugh this morning at the email address on his GitHub account (and in his commits). I'll comment her if he replies.

**Comment by gene1wood** [comment]
So I've heard nothing back from @jpaugh . I emailed him again just now but I'm not hopeful. If I don't hear something tomorrow I'll fork into the mozilla organization and we can try moving from there. I've got a branch that I'm using that adds support for GitHub pagination and ratelimit management into the GitHub client piece which I really like.

**Comment by jaredhobbs** [comment]
When that happens, let me know the pypi username and I'll transfer control.

**Comment by gene1wood** [comment]
Ok, no response from @jpaugh so I've forked to https://github.com/mozilla/agithub

@jaredhobbs If you'd like to transfer pypi control to me for now I'm happy to take it and if there is more interest from other folks to help with either maintaining or packaging (pypi) in the future I can transfer to them at that time if need be.

I'm [`gene1wood`](https://pypi.python.org/pypi?%3Aaction=search&term=gene1wood&submit=search) on pypi.

Feel free to open [PRs](https://github.com/mozilla/agithub/pulls) on the fork. I'll look through the issues that are open here and either ask the issue authors if they'd like to open them on the fork or just copy paste them.

**Comment by jaredhobbs** [comment]
OK, I added you as an owner on pypi.

**Comment by lofidevops** [comment]
Created straw poll for renaming at https://github.com/mozilla/agithub/issues/37 (ends April 1 23:59 AoE)

**Comment by jpaugh** [comment]
@gene1wood Hi, Gene. I've created an org account for AGithub, and invited you as an owner. I suspect it will be easy to migrate to mozilla at that point, but I don't think I can do that without being a member. I hope AGithub will find a better home at Mozilla, and I'm glad that you're interested.

It's been really hard to say goodbye to this project, and I apologize for being unresponsive. I never expected it to affect me so deeply when I opened this issue in November.

**Comment by gene1wood** [comment]
I've transferred the repo to the mozilla org.

@jpaugh Would you like to remain an admin of the repo? If I don't hear anything I'll assume you're good for now and don't need to be an admin (and at any time you're welcome to contact me to be added)

> I can volunteer some time to help with pull requests and issues where needed.

@nnja Would you like write access to help with PRs and issues?

> You could also consider admin and maintenance support from @jazzband

@kwill As that's an org, would you like to help with reviewing/merging PRs and managing issues yourself or were you just saying that the jazzband org could act as a transfer destination?

**Comment by nnja** [comment]
@gene1wood yes, I'd be happy to help with PRs and issues, starting in a few weeks. I'm currently out of the country until the end of March, and won't be able to participate until I'm back.

**Comment by lofidevops** [comment]
@gene1wood That was just a suggestion for a destination. I'm not able to help with maintenance at this time, but you can expect bug reports and PRs :)

**Comment by gene1wood** [comment]
@nnja Great, I've added you as a writer

@kwill Got it, no worries.

I'll close this ticket out as we've succeeded in transferring ownership of the repo and pypi package. If others are open to helping take tickets, review/merge PRs, feel free to open an issue requesting access and volunteering to help.
