### ISSUE TITLE
Straw poll: more encompassing name (ends April 1 23:59)

### ISSUE THREAD

**Issue by gene1wood** [mozilla/agithub#37]
This project is no longer limited to just the Github REST API, so a more encompassing name is appropriate. Please submit suggestions below and vote below.

* One suggestion per comment: shortname/Long Name
* Vote with thumbs up or down (others ignored)
* Suggestion window ends April 1 23:59 [AoE](https://en.wikipedia.org/wiki/Anywhere_on_Earth)
* Final decision (tie-breaking, valid entry, veto, etc) by @gene1wood

**Comment by gene1wood** [comment]
2 suggestions from @kwill 

* arestclient/Agnostic REST client
* agithub/The Agnostic GitHub API (in other words, don't change it)

**Comment by lofidevops** [comment]
arestclient/Agnostic REST client

**Comment by lofidevops** [comment]
agithub/The Agnostic GitHub API (in other words, don't change it)

**Comment by nnja** [comment]
papi/Portable API client

**Comment by nnja** [comment]
wrapi/Lightweight API wrapper

**Comment by gene1wood** [comment]
Alright, not a lot of participation (just the three of us). Looks like @kwill and I liked `arestclient/Agnostic REST client` which is enough to make it the top voted :rofl: 

I'll close this out with an intent to rename to `arestclient/Agnostic REST client`. I'm assuming you're both ok with getting to this over the next month or so (want to make a graceful dependency transition from the old pypi package name to the new, and probably a lot of renaming of things inside the code that reference `agithub`).

I'm also fine with, in the intervening time, some groundswell of interest in a different name considering the very very small sample size of the three of us.

I've squated [`arestclient`](https://pypi.python.org/pypi/arestclient/0.0.1) on pypi for good measure.

**Comment by nnja** [comment]
👌 with me! I'd love to get together to chat for a few minutes about the direction of this project -- what we want to do with open issues and PRs, style guides, potentially setting up CI. Is there a preferred medium?

**Comment by pyther** [comment]
If it would be helpful, I can attempt to rename things appropriately and submit a pull request.
