### ISSUE TITLE
How to handle endpoints with operator characters such as '-', '+', etc.?

### ISSUE THREAD

**Issue by mhorlacher** [mozilla/agithub#81]
E.g.:

- endpoint: `/products/ABC-DEF`

- agithub: `api.products.ABC-DEF`  <-- Invalid

**Comment by gene1wood** [comment]
You should be able to by using what's shown in [step 4 in the example](https://github.com/mozilla/agithub#example-app)

```
api.products['ABC-DEF']
```

**Comment by mhorlacher** [comment]
@gene1wood Thanks, I was a bit confused I assumed `products` is some sort of collection that get queried, but figured it out now.
