### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [mozilla/agithub#82]
Hi there,

I couldn't find a `SECURITY.md` in your repository and am not sure how to best contact you privately to disclose a security issue.

Can you add a `SECURITY.md` file with an e-mail to your repository, so that our system can send you the vulnerability details? GitHub suggests that a [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) is the best way to make sure security issues are responsibly disclosed.

Once you've done that, you should receive an e-mail within the next hour with more info.

Thanks! (cc @huntr-helper)

**Comment by gene1wood** [comment]
Sure thing, I've added a SECURITY.md in #83

**Comment by gene1wood** [comment]
The [security issue](https://huntr.dev/bounties/1626073357089-mozilla/agithub/) that was reported by @michaellrowley was invalid. He was pointing out that the [README contains an IP address which is a disclosure of private information](https://cwe.mitre.org/data/definitions/540.html). The IP address is an address [designated by IANA for purposes of documentation](https://datatracker.ietf.org/doc/html/rfc5737) and is there intentionally.
